-- =====================================================================
-- ATTENDANCE SYSTEM — SUPABASE / POSTGRESQL SCHEMA
-- =====================================================================
-- Paste this into Supabase SQL Editor (Project → SQL Editor → New query).
-- Run once. It creates all tables, indexes, and seed values.
--
-- Conventions:
--   - All IDs are UUID, generated by Postgres.
--   - All timestamps are timestamptz (timezone-aware).
--   - Soft deletes via `is_active` flag where useful, hard deletes only
--     for transient logs.
-- =====================================================================

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =====================================================================
-- 1. TEAMS
-- =====================================================================
CREATE TABLE teams (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name            TEXT NOT NULL UNIQUE,         -- "Engineering", "Design", "Sales"
  lead_id         UUID,                          -- FK to employees.id, set after employees seeded
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =====================================================================
-- 2. EMPLOYEES
-- =====================================================================
CREATE TYPE employee_role AS ENUM ('employee', 'team_lead', 'hr', 'admin');

CREATE TABLE employees (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name         TEXT NOT NULL,
  email             TEXT NOT NULL UNIQUE,
  slack_user_id     TEXT UNIQUE,                 -- e.g. "U02ABCD1234" — set when bot first sees them
  team_id           UUID REFERENCES teams(id) ON DELETE SET NULL,
  role              employee_role NOT NULL DEFAULT 'employee',
  join_date         DATE NOT NULL,
  -- Yearly leave allowances. JSON so HR can tweak per-employee without a schema change.
  -- Default values match: Casual 10, Sick 8, Annual 14.
  leave_allowances  JSONB NOT NULL DEFAULT '{"casual": 10, "sick": 8, "annual": 14}'::jsonb,
  is_active         BOOLEAN NOT NULL DEFAULT true,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Now that employees exists, add the FK on teams.lead_id
ALTER TABLE teams ADD CONSTRAINT fk_team_lead
  FOREIGN KEY (lead_id) REFERENCES employees(id) ON DELETE SET NULL;

CREATE INDEX idx_employees_slack ON employees(slack_user_id);
CREATE INDEX idx_employees_team  ON employees(team_id);

-- =====================================================================
-- 3. ATTENDANCE LOGS
-- One row per employee per day. Auto-logged from Slack OR submitted via UI.
-- =====================================================================
CREATE TYPE attendance_type   AS ENUM ('present', 'wfh', 'ewd', 'half_leave', 'full_leave', 'sick', 'holiday');
CREATE TYPE attendance_half   AS ENUM ('full', 'first_half', 'second_half');
CREATE TYPE attendance_status AS ENUM ('auto_logged', 'pending', 'approved', 'rejected', 'confirmed');

CREATE TABLE attendance_logs (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id       UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  date              DATE NOT NULL,
  type              attendance_type NOT NULL,
  half              attendance_half NOT NULL DEFAULT 'full',
  reason            TEXT,
  status            attendance_status NOT NULL DEFAULT 'auto_logged',
  source            TEXT NOT NULL DEFAULT 'slack',  -- 'slack' | 'web' | 'slash_command' | 'hr_manual'
  slack_message_ts  TEXT,                            -- Slack message timestamp, if from bot
  created_by        UUID REFERENCES employees(id),   -- who created the entry
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- One entry per employee per date (override via UPSERT)
  UNIQUE (employee_id, date)
);

CREATE INDEX idx_attendance_employee_date ON attendance_logs(employee_id, date DESC);
CREATE INDEX idx_attendance_date          ON attendance_logs(date DESC);
CREATE INDEX idx_attendance_status        ON attendance_logs(status);

-- =====================================================================
-- 4. LEAVE REQUESTS
-- Used only for FULL leaves (per your rule: only full leaves need approval).
-- Half / WFH / EWD bypass this and write directly to attendance_logs.
-- =====================================================================
CREATE TYPE leave_type   AS ENUM ('casual', 'sick', 'annual');
CREATE TYPE leave_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled');

CREATE TABLE leave_requests (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  employee_id  UUID NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  type         leave_type NOT NULL,
  from_date    DATE NOT NULL,
  to_date      DATE NOT NULL,
  reason       TEXT,
  status       leave_status NOT NULL DEFAULT 'pending',
  approver_id  UUID REFERENCES employees(id),  -- the team lead OR hr who acted
  decided_at   TIMESTAMPTZ,
  decision_note TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (to_date >= from_date)
);

CREATE INDEX idx_leave_requests_employee ON leave_requests(employee_id);
CREATE INDEX idx_leave_requests_status   ON leave_requests(status);
CREATE INDEX idx_leave_requests_dates    ON leave_requests(from_date, to_date);

-- =====================================================================
-- 5. HOLIDAYS
-- Public holidays + weekends config. Used to exclude from attendance counts.
-- =====================================================================
CREATE TABLE holidays (
  id      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date    DATE NOT NULL UNIQUE,
  name    TEXT NOT NULL,
  is_optional BOOLEAN NOT NULL DEFAULT false  -- e.g. religious optional holidays
);

-- =====================================================================
-- 6. SLACK PARSE LOG
-- Every Slack message the bot sees in #attendance. For debugging the parser
-- and improving it over time.
-- =====================================================================
CREATE TYPE parse_method AS ENUM ('regex', 'claude_api', 'slash_command', 'failed');

CREATE TABLE slack_parse_log (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slack_user_id       TEXT NOT NULL,
  slack_channel_id    TEXT NOT NULL,
  slack_message_ts    TEXT NOT NULL,
  raw_text            TEXT NOT NULL,
  method              parse_method NOT NULL,
  parsed_type         attendance_type,
  parsed_half         attendance_half,
  parsed_date         DATE,
  parsed_reason       TEXT,
  confidence          NUMERIC(3,2),                -- 0.00–1.00
  attendance_log_id   UUID REFERENCES attendance_logs(id) ON DELETE SET NULL,
  awaiting_confirm    BOOLEAN NOT NULL DEFAULT false,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (slack_message_ts, slack_channel_id)
);

CREATE INDEX idx_parse_log_user      ON slack_parse_log(slack_user_id);
CREATE INDEX idx_parse_log_awaiting  ON slack_parse_log(awaiting_confirm) WHERE awaiting_confirm = true;

-- =====================================================================
-- 7. AUDIT LOG
-- Who changed what, when. Light-touch — only for sensitive ops (approvals,
-- balance adjustments, manual overrides).
-- =====================================================================
CREATE TABLE audit_log (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id    UUID REFERENCES employees(id),
  action      TEXT NOT NULL,                  -- e.g. "approved_leave", "edited_attendance", "adjusted_balance"
  target_type TEXT,                           -- "leave_request", "attendance_log", "employee"
  target_id   UUID,
  details     JSONB,                          -- old/new values, free-form
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_actor ON audit_log(actor_id, created_at DESC);

-- =====================================================================
-- VIEWS — convenience queries for the app
-- =====================================================================

-- Per-employee leave balance, computed live from approved leaves this year.
CREATE OR REPLACE VIEW v_employee_balances AS
SELECT
  e.id AS employee_id,
  e.full_name,
  (e.leave_allowances->>'casual')::int AS casual_allowance,
  COALESCE((SELECT SUM(to_date - from_date + 1) FROM leave_requests
            WHERE employee_id = e.id AND type = 'casual' AND status = 'approved'
              AND EXTRACT(YEAR FROM from_date) = EXTRACT(YEAR FROM CURRENT_DATE)), 0) AS casual_used,
  (e.leave_allowances->>'sick')::int AS sick_allowance,
  COALESCE((SELECT SUM(to_date - from_date + 1) FROM leave_requests
            WHERE employee_id = e.id AND type = 'sick' AND status = 'approved'
              AND EXTRACT(YEAR FROM from_date) = EXTRACT(YEAR FROM CURRENT_DATE)), 0) AS sick_used,
  (e.leave_allowances->>'annual')::int AS annual_allowance,
  COALESCE((SELECT SUM(to_date - from_date + 1) FROM leave_requests
            WHERE employee_id = e.id AND type = 'annual' AND status = 'approved'
              AND EXTRACT(YEAR FROM from_date) = EXTRACT(YEAR FROM CURRENT_DATE)), 0) AS annual_used
FROM employees e
WHERE e.is_active = true;

-- Today's status for everyone, for the HR team grid.
CREATE OR REPLACE VIEW v_today_status AS
SELECT
  e.id AS employee_id,
  e.full_name,
  t.name AS team_name,
  COALESCE(a.type::text, 'unmarked') AS status,
  a.half,
  a.reason
FROM employees e
LEFT JOIN teams t ON e.team_id = t.id
LEFT JOIN attendance_logs a ON a.employee_id = e.id AND a.date = CURRENT_DATE
WHERE e.is_active = true
ORDER BY t.name, e.full_name;

-- =====================================================================
-- SEED DATA — Pakistan public holidays for 2026 (sample, edit as needed)
-- =====================================================================
INSERT INTO holidays (date, name) VALUES
  ('2026-02-05', 'Kashmir Day'),
  ('2026-03-23', 'Pakistan Day'),
  ('2026-05-01', 'Labour Day'),
  ('2026-08-14', 'Independence Day'),
  ('2026-12-25', 'Quaid-e-Azam Day / Christmas')
ON CONFLICT (date) DO NOTHING;

-- =====================================================================
-- DONE.
-- Next: enable Row Level Security policies (Claude Code will write these
-- once the auth layer is wired up — they depend on Supabase auth.uid()).
-- =====================================================================
